-- Create Database
CREATE DATABASE CertificateDB;
GO

USE CertificateDB;
GO

-- 1. Table: Users (Admin)
CREATE TABLE Users (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL, -- Store hashed password
    FullName NVARCHAR(100) NOT NULL,
    Role NVARCHAR(20) DEFAULT 'Admin',
    WalletAddress NVARCHAR(100) -- MetaMask wallet address
);
GO

-- 2. Table: Certificates (Metadata)
CREATE TABLE Certificates (
    CertId INT IDENTITY(1,1) PRIMARY KEY,
    CertCode NVARCHAR(50) NOT NULL UNIQUE,
    RecipientName NVARCHAR(100) NOT NULL,
    CourseName NVARCHAR(200),
    IssueDate DATETIME DEFAULT GETDATE(),
    IssuerName NVARCHAR(100) NOT NULL,
    IpfsCID NVARCHAR(100) NOT NULL, -- Link IPFS của file PDF
    FileHash NVARCHAR(100) NOT NULL UNIQUE, -- SHA-256 hash của PDF
    Status NVARCHAR(20) DEFAULT 'Valid' -- 'Valid' hoặc 'Revoked'
);
GO

-- 3. Table: VerificationHistory
CREATE TABLE VerificationHistory (
    HistoryId INT IDENTITY(1,1) PRIMARY KEY,
    CertCode NVARCHAR(50), -- có thể tra cứu sai mã nên ko FK
    VerifyTime DATETIME DEFAULT GETDATE(),
    IPAddress NVARCHAR(50),
    IsSuccess BIT -- 1: Hợp lệ, 0: Không hợp lệ
);
GO

-- Insert default admin (Password: admin123, hash will be generated by bcrypt in Node.js)
-- Tạm để admin / admin cho test dễ, khi code Node.js sẽ dùng bcrypt
INSERT INTO Users (Username, PasswordHash, FullName, WalletAddress)
VALUES ('admin', '$2b$10$w81.mP8gqJ./Yh3v/4hDVuK7eO1C9XfRk6g8H4XN1w7Q6qM3P9H5i', 'Administrator', '');
-- (Bcrypt hash của 'admin123' là $2b$10$w81.mP8gqJ./Yh3v/4hDVuK7eO1C9XfRk6g8H4XN1w7Q6qM3P9H5i)
GO
